# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  variable "upg_sso_realm_id" {
    description = "id of the parent realm"
  }

  variable "upg_sso_realm_client_id" {
    description = "client_id of the child client on the parent realm (upg-sso)"
  }

  variable "project" {
    description = "project name"
    default     = "up"
  }

  variable "subproject" {
    description = "subproject name"
    default     = "idp"
  }

  variable "env" {
    description = "environment"
  }

  variable "keycloak_url" {
    description = "keycloak url"
  }

  variable "keycloak_client_id" {
    description = "keycloak client id"
    default     = "admin-cli"
  }

  variable "keycloak_user" {
    description = "keycloak user"
    default     = "admin"
  }

  variable "keycloak_password" {
    description = "keycloak user password"
  }
