# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
    required_version = ">= 0.14"

    required_providers {
      keycloak = {
        source  = "mrparkers/keycloak"
        version = ">= 2.3.0"
      }
      aws = {
        source  = "hashicorp/aws"
        version = ">= 2.70"
      }
    }
  }

  provider "keycloak" {
    username  = var.keycloak_user
    password  = var.keycloak_password
    client_id = var.keycloak_client_id
    url       = var.keycloak_url
  }

provider "aws" {
    access_key                  = "mock_access_key"
    region                      = "us-east-1"
    s3_force_path_style         = true
    secret_key                  = "mock_secret_key"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true

    endpoints {
      secretsmanager = "http://localstack.aws.prod.fabaleus.com:4566"
      s3             = "http://localstack.aws.prod.fabaleus.com:4566"
    }
  }
